# general settings
name: 002_ESRGAN_x4_PLANET_pretrainDF2K_wandb_sep5
model_type: ESRGANModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: PLANET_TRAIN
    type: PairedImageDataset
    #dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    #dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
    # (for lmdb)
    dataroot_gt: /data_dir/train_mod/HR/x4 #PLANET_HR_x4_train.lmdb #HR #datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    dataroot_lq: /data_dir/train_mod/LR/x4 #PLANET_LR_x4_train.lmdb #LR #datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      #type: lmdb

    gt_size: 128
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: PLANET_VAL
    type: PairedImageDataset
    dataroot_gt: /data_dir/valid_mod/HR/x4 #HR #datasets/Set14/GTmod12
    dataroot_lq: /data_dir/valid_mod/LR/x4 #LR #datasets/Set14/LRbicx4
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23

network_d:
  type: VGGStyleDiscriminator128
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_model_g: ~ #/data_dir/pixel-smasher/ESRGAN_PSNR_SRx4_DF2K_official-150ff491.pth #experiments/051_RRDBNet_PSNR_x4_f64b23_DIV2K_1000k_B16G1_wandb/models/net_g_1000000.pth
  strict_load: true
  resume_state: /data_dir/pixel-smasher/experiments/002_ESRGAN_x4_PLANET_pretrainDF2K_wandb_sep5/training_states/10000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 1.0
    style_weight: 0
    norm_img: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: pixelsmasher
    resume_id: resume_0

# dist training settings
dist_params:
  backend: nccl
  port: 29500
