#### general settings
name: 003_RRDB_ESRGANx4_PLANET
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: PLANET
    mode: LQGT
    dataroot_GT: /data_dir/train_HR.lmdb
    dataroot_LQ: /data_dir/train_LR.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val_set14_part
    mode: LQGT
    dataroot_GT: /data_dir/valid_mod/HR/x4/ #/mnt/SSD/xtwang/BasicSR_datasets/val_set14_part/Set14
    dataroot_LQ: /data_dir/valid_mod/LR/x4/ #/mnt/SSD/xtwang/BasicSR_datasets/val_set14_part/Set14_bicLRx4

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  #edited for resume state 500
  pretrain_model_G: /pixel-smasher/experiments/003_RRDB_ESRGANx4_PLANET/models/500_G.pth #/home/ekaterina_lezine/pixel-smasher/RRDB_PSNR_x4.pth
  strict_load: true
  resume_state: /home/ekaterina_lezine/pixel-smasher/experiments/003_RRDB_ESRGANx4_PLANET/training_state/500.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 100000
  warmup_iter: -1  # no warm up
  lr_steps: [5000, 20000, 40000, 70000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 5000 #!!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 500
